-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS "Stock"."CurrentStock" DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS "Stock"."ArchivedStock" DROP CONSTRAINT IF EXISTS None;



DROP TABLE IF EXISTS "Stock"."CurrentStock";

CREATE TABLE IF NOT EXISTS "Stock"."CurrentStock"
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    "Worker" character varying(5) DEFAULT null,
    "Week" character varying(4) NOT NULL,
    "Location" character varying(20) DEFAULT null,
    "Recipients" integer,
    "PPR" integer NOT NULL DEFAULT 1,
    "Category" integer,
    "Phase" integer,
    "Health" integer,
    "History" text NOT NULL,
    "Remarks" text,
    "Plant_code" character varying(10) NOT NULL,
    "Medium_id" integer NOT NULL,
    PRIMARY KEY ("Id")
);

DROP TABLE IF EXISTS "Stock"."ArchivedStock";

CREATE TABLE IF NOT EXISTS "Stock"."ArchivedStock"
(
    "Reason" character varying(20) NOT NULL
) INHERITS ("Stock"."CurrentStock");

COMMENT ON COLUMN "Stock"."CurrentStock"."Worker"
    IS 'Null = extern';

COMMENT ON COLUMN "Stock"."CurrentStock"."PPR"
    IS 'Plants Per Recipient';

DROP TABLE IF EXISTS "Stock"."Plant";

CREATE TABLE IF NOT EXISTS "Stock"."Plant"
(
    "Code" character varying(10) NOT NULL,
    PRIMARY KEY ("Code")
);

DROP TABLE IF EXISTS "Stock"."Medium";

CREATE TABLE IF NOT EXISTS "Stock"."Medium"
(
    "Id" integer NOT NULL,
    "Description" text,
    PRIMARY KEY ("Id")
);

ALTER TABLE IF EXISTS "Stock"."CurrentStock"
    ADD FOREIGN KEY ("Plant_code")
    REFERENCES "Stock"."Plant" ("Code") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "Stock"."CurrentStock"
    ADD FOREIGN KEY ("Medium_id")
    REFERENCES "Stock"."Medium" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
